# Site settings
title: Test blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://epgauss.github.io"
twitter_username: epauss
github_username:  epgaussy

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
